#!/bin/bash
set -o errexit

REPOSITORY=docker.io/castedo/nests
NEST=amazon-1
CUSER=$USER
if [[ $CUSER == "root" ]]; then
  CUSER=$1
fi
HOME=$(eval echo ~$CUSER)

build-nest-image $REPOSITORY:$NEST localnests:$NEST "$CUSER"

create-nest localnests:$NEST $NEST "$CUSER" \
  --network host \
  --hostname $HOSTNAME \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --device /dev/snd \
  --device /dev/dri

