#!/bin/bash
set -o errexit

if [[ -z "$3" ]]; then
  THIS_SCRIPT=$'\u001b[1m'"$(basename $0)"$'\u001b[0m'
  echo "Usage: $THIS_SCRIPT base_image nest_name user [extra_groups]"
  exit 1
fi

BASE_IMAGE=$1
shift
NEST_IMAGE=$1
shift
CUSER=$1
shift
EXTRA_GROUPS="$@"

if podman image exists "$NEST_IMAGE"; then
  echo "Skipping build of existing image: $NEST_IMAGE"
  exit
fi

CUID=$(id -u $CUSER)
TMP=$(buildah from "$BASE_IMAGE")
buildah run $TMP -- useradd --create-home --user-group --uid $CUID $CUSER
if [[ -n "$EXTRA_GROUPS" ]]; then
  buildah run $TMP -- usermod -a -G $EXTRA_GROUPS $CUSER
fi
buildah config --user $CUSER --workingdir /home/$CUSER $TMP
buildah commit $TMP "$NEST_IMAGE"
buildah rm $TMP

