#!/bin/bash
set -o errexit

if [[ -z "$2" ]]; then
  THIS_SCRIPT=$'\u001b[1m'"$(basename $0)"$'\u001b[0m'
  echo "Usage: $THIS_SCRIPT image container_name [extra_podman_options]"
  exit 1
fi

IMAGE="$1"
shift
NAME="$1"
shift
EXTRA_OPTIONS="$@"

podman create \
  --userns=keep-id \
  --security-opt label=disable \
  --pid host \
  --name "$NAME" \
  $EXTRA_OPTIONS \
  $IMAGE \
  sleep +Inf

