site_name: A Minimalist's Guide to Persistent Personalized Containers
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/castedo/cnest
edit_uri: edit/main/docs
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
markdown_extensions:
  - admonition
nav:
  - Introduction: index.md
  - podman.md
  - The Cnest Package:
    - install.md
    - cnest-tools.md
    - tips.md
  - How-To Guides:
    - how-to-share-partial-home.md
  - temp-containers.md
  - other-tools.md
  - history.md
