site_name: The Cnest Guide to Personal Multisession Containers
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/castedo/cnest
edit_uri: edit/main/docs
theme:
  name: material
  features:
    - content.action.edit
    - navigation.footer
markdown_extensions:
  - admonition
  - tables
nav:
  - Introduction: index.md
  - podman.md
  - install.md
  - Tutorials:
    - Start: tutorial/start.md
    - Saving Personalizations: tutorial/saving.md
  - How-To Guides:
    - Enable Sudo: howto/sudo.md
    - Stow home config file: howto/stow.md
  - caveats.md
  - tips.md
  - cnest-tools.md
  - temp-containers.md
  - other-tools.md
  - history.md
