site_name: The Cnest Guide to Nest Containers
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/castedo/cnest
edit_uri: edit/main/docs
theme:
  name: readthedocs
  features:
    - content.action.edit
    - navigation.footer
nav:
  - Home: index.md
  - INTRODUCTION:
    - what-are-nest-containers.md
    - other-tools.md
  - HOW-TO GUIDES:
    - how-to-share-partial-home.md
  - THE CNEST PACKAGE:
    - install.md
    - cnest-tools.md
    - tips.md
    - conclusions.md
