#!/bin/bash
if ! id -u "$1" &>/dev/null; then
    echo parameter passed is invalid user: $1
    exit 22 # EINVAL Invalid argument
fi
mkdir --parents /home/$1
chown $1: /home/$1
usermod --home /home/$1 $1
passwd --delete $1
