#!/bin/bash
set -o errexit

REPOSITORY=docker.io/castedo/nests
NEST=chromed-3
CUSER=$USER
if [[ $CUSER == "root" ]]; then
  CUSER=$1
fi

../../build-nest-image $REPOSITORY:$NEST localnests:$NEST "$CUSER" audio,video

HOME=$(eval echo ~$CUSER)

../../create-nest localnests:$NEST $NEST "$CUSER" \
  --hostname chromed-$HOSTNAME \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /dev/shm:/dev/shm \
  -v /etc/machine-id:/etc/machine-id \
  --device /dev/snd \
  --device /dev/dri \
  -v $HOME/Downloads:/home/$CUSER/Downloads

